version: "3"
volumes:
  db-store:
  php-fpm-socket:
services:
  app:
    build: ./docker/php
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../:/workspace:cached
  db:
    image: mysql:8
    volumes:
      - ./docker/mysql/my.cnf:/etc/my.cnf
      - db-store:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
      MYSQL_DATABASE: laravel
  web:
    image: nginx:alpine
    ports:
      - 8000:80
    working_dir: /workspace
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - php-fpm-socket:/var/run/php-fpm
      - ../:/workspace:cached
